#!/bin/bash

# create-turo-secret.sh
# Shell script to create Turo credentials in AWS Secrets Manager
# Generated by @Infra-Agent per CLAUDE_ORCHESTRATOR.md

set -e  # Exit on any error

echo "🔐 Turo Credentials Setup for AWS Secrets Manager"
echo "================================================"
echo

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ Error: AWS CLI is not installed or not in PATH"
    echo "Please install AWS CLI first: https://aws.amazon.com/cli/"
    exit 1
fi

# Check if AWS credentials are configured
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ Error: AWS credentials not configured"
    echo "Please run 'aws configure' first to set up your AWS credentials"
    exit 1
fi

echo "✅ AWS CLI found and credentials configured"
echo

# Prompt for Turo credentials
echo "Please enter your Turo host dashboard credentials:"
echo

read -p "Turo Email: " TURO_EMAIL

# Validate email format
if [[ ! "$TURO_EMAIL" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
    echo "❌ Error: Invalid email format"
    exit 1
fi

# Prompt for password securely (no echo)
read -s -p "Turo Password: " TURO_PASSWORD
echo
echo

# Validate password is not empty
if [[ -z "$TURO_PASSWORD" ]]; then
    echo "❌ Error: Password cannot be empty"
    exit 1
fi

# Create temporary credentials file
TEMP_FILE="turo-creds.json"
echo "📝 Creating temporary credentials file..."

cat > "$TEMP_FILE" << EOF
{
  "email": "$TURO_EMAIL",
  "password": "$TURO_PASSWORD"
}
EOF

echo "✅ Temporary file created: $TEMP_FILE"
echo

# Create the secret in AWS Secrets Manager
echo "🚀 Creating secret in AWS Secrets Manager..."
echo "Secret name: turo-ezpass/turo/credentials"
echo

if aws secretsmanager create-secret \
    --name turo-ezpass/turo/credentials \
    --description "Turo host dashboard login creds" \
    --secret-string file://"$TEMP_FILE"; then
    
    echo "✅ Secret created successfully in AWS Secrets Manager!"
    
else
    echo "❌ Failed to create secret. The secret may already exist."
    echo "To update existing secret, use:"
    echo "aws secretsmanager update-secret --secret-id turo-ezpass/turo/credentials --secret-string file://$TEMP_FILE"
    
    # Clean up temp file before exit
    rm -f "$TEMP_FILE"
    exit 1
fi

# Clean up temporary file
echo
echo "🧹 Cleaning up temporary file..."
rm -f "$TEMP_FILE"

if [[ ! -f "$TEMP_FILE" ]]; then
    echo "✅ Temporary file deleted successfully"
else
    echo "⚠️  Warning: Could not delete temporary file $TEMP_FILE"
fi

echo
echo "🎉 Setup complete! Your Turo credentials are now stored securely in AWS Secrets Manager."
echo "The scrapers and TuroBot can now retrieve these credentials automatically."
echo
echo "Secret ARN: arn:aws:secretsmanager:$(aws configure get region):$(aws sts get-caller-identity --query Account --output text):secret:turo-ezpass/turo/credentials"
echo