name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'app/scripts/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./app/scripts
      run: npm ci
      
    - name: Install Playwright browsers
      working-directory: ./app/scripts
      run: npx playwright install --with-deps
      
    - name: Run tests
      working-directory: ./app/scripts
      run: npm test
      
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::486365525776:role/turo-ezpass-github-actions-role
        aws-region: us-east-1
        role-session-name: GitHubActions-CI-Test
      
    - name: Run E-ZPass scraper
      working-directory: ./app/scripts
      run: npm run scrape-ezpass
      
    - name: Run Turo scraper
      working-directory: ./app/scripts
      run: npm run scrape-turo
      
    - name: Upload debug screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: |
          app/scripts/scrapers/screenshots/
          app/scripts/failure-screenshots/
        retention-days: 30