name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'app/scripts/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./app/scripts
      run: npm ci
      
    - name: Install Playwright browsers
      working-directory: ./app/scripts
      run: npx playwright install --with-deps
      
    - name: Run tests
      working-directory: ./app/scripts
      run: npm test
      
    - name: Run E-ZPass scraper with mock credentials
      working-directory: ./app/scripts
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: npm run scrape-ezpass
      
    - name: Run Turo scraper with mock credentials
      working-directory: ./app/scripts
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: npm run scrape-turo
      
    - name: Upload debug screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: |
          app/scripts/scrapers/screenshots/
          app/scripts/failure-screenshots/
        retention-days: 30