name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'app/scripts/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./app/scripts
      run: npm ci
      
    - name: Run tests
      working-directory: ./app/scripts
      run: npm test
      
    # TODO: Add linting, type checking, or other static analysis here
    # - name: Run linter
    #   working-directory: ./app/scripts
    #   run: npm run lint